routes:
  - name: odoo11-waf
    domain: kmgetubs19.ch
    dns_resolver: "cf-production"
    port: 8069
    portSecure: 8069
  - name: odoo11-waf
    domain: kmgetubs19.sharevic.net
    dns_resolver: "cf-production"
    port: 8069
    portSecure: 8069
  - name: odoo11-waf
    domain: www.kmgetubs19.ch
    dns_resolver: "cf-production"
    port: 8069
    portSecure: 8069

odoo11-waf:
  replicaCount: 0
  image:
    repository: luechtdiode/nginx-naxsi
    tag: v1.0.0
  network:
    http:
      containerPort: 80
      servicePort: 8069
  service:
    type: NodePort
  resources:
    requests:
      cpu: 0.5
      memory: 128Mi
    limits:
      cpu: 0.5
      memory: 512Mi
  volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-cm

odoo11:
  replicaCount: 0
  image:
    repository: docker.io/library/odoo@sha256
    tag: e56217f82eb5579e1b54f37b18396f4b1666d42be8b1cfced85dc4383c33cb49
  readinessProbe:
    httpGet:
      path: /
      port: 8069
    initialDelaySeconds: 10
  timeoutSeconds: 1    
  network:
    http:
      servicePort: 8069
      # ingress:
      #  host: competition.sharevic.net
  service:
    type: NodePort
  resources:
    requests:
      cpu: 500m
      memory: 0.5Gi
    limits:
      memory: 1Gi
  defaultAffinityRules:
    enabled: false
  volumes:
    - name: odoo-web-data
      persistentVolumeClaim:
        claimName: odoo-web-data  
    - name: config-cm
      configMap:
        name: odoo-config
  volumeMounts:
    - mountPath: /var/lib/odoo
      subPath: webdata
      name: odoo-web-data
    - mountPath: /etc/odoo/odoo.conf
      name: config-cm
      subPath: odoo.conf
    - mountPath: /mnt/extra-addons
      subPath: odooaddons
      name: odoo-web-data
