apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: docker-registry-secret
spec:
  encryptedData:
    .dockerconfigjson: AgCjsWMsJs8FGsLkqGn3zDeSspiWEDwAkBRYpYkPKLHnLp5cC6n7KLvSyOosMuIZ65c6rbpOsFkgQTxHJisfgeghPpEBpcsb8lz5mECOfQGJvoFJLmxYdSnk9/I2Nrd+VF56x/YaQv6IKaTJ5YQmNrSz4bOMdQS7FDQXb72EboVKrGQSoRxyfCprDIiihR+8mzgRnvPEn1lw+P5b3Vb1TDO7lyxkZHdiJ8MvbmCIoNSwwA4YLDYHYQr58+jbiCdHx7oPfiSGCAykU1ApJ7sCpelqkmJzxAshTRF18kmrbvKE4XNPu7YdqyLkwz5Ra+W3jDIl2Bn/93ksQ0JrWUGLdLnZ2ymykvcqf/35Pg44c39eBCGWQjJN67g8ucZPx0EgVEtPJU76rvSMEGmh60I2mWAuU5EeSiL/o3QKhMrulokK9JqKT0ANk+Y+hYozP3Rtehy5gdDie0U3KFRKUj477c9x0nfrv3wlHe69NH6/thqFYPaQV7wBtCAMuc4dRKgjIJCZlPvi/7//5+NVJrEJmuXpBqIj4cSwDqZWgKNuAJQScPxgqDAOKWIsTWRFDHtAzOrS2m2eJNiii5aG/QxKoPmYj1FruTMmAOnqi1cz3sUFPiseEH+5H+/LpZ4g2iSNM7r67Oy7UuOVqWGif8Gsrs9tQqxkgVw2XbubkiPHSLFhQmyRnUsCI04PWepAKLfbPqEyexMt+VyxihtXDU+asXPu0vFDrpWb9SLQFkgTpKzLv2gvyDj+7DY/tvPVCLoukrsZrp+NXSgy3zo8xJ52F/RkEd29KEVo6m4UyPRezNlBoIoYa7/KZ0oo+vdAjG+yeFnaSj9PjKogBA7W9t3COnYEOWLOnIM/B/+MoSzcktfbjy+7kFQ0CigBF2DdYxSmoBjeZ/sl0I9IZOtiIaEL0rMGe01iQje9AkC34QPdnurnQ8GPlnfup8m44QDCM8qnvw3bFhuMgj8gNYy/eEtS50ofDQoLDHhzdxDj1KeCkDWwhac=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: docker-registry-secret
    type: kubernetes.io/dockerconfigjson