apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  jetstream:
    version:
      2.10.10 # https://console.baloise.dev/k8s/ns/argo-events/configmaps/argo-events-controller-config/yaml