apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kutuapp-test-sm
  namespace: kutuapp-test
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: kutuapp
  endpoints:
  - port: http
    interval: 10s
  namespaceSelector:
    matchNames:
      - kutuapp-test
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus  