{{ range .Values.routes }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: https-route-{{ .domain }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ trimPrefix "https://" .domain }}`)
      kind: Rule
      priority: 5 
      services:
      - kind: Service
        name: {{ .name }}
        port: {{ .port }}
      middlewares:
        - name: secure
          namespace: traefik
{{ end }}

