{{ if .Values.installroute }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-ingress-route
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: 'HostRegexp(`{subdomain:argo}.interpolar.ch`)'
      middlewares:
        - name: security-response-header
          namespace: traefik
        - name: more-security-response-header
          namespace: traefik
      priority: 10
      services:
        - name: argocd-server
          port: 443
    - kind: Rule
      match: >-
        Host(`argo.interpolar.ch`) && Headers(`Content-Type`,
        `application/grpc`)
      middlewares:
        - name: security-response-header
          namespace: traefik
        - name: more-security-response-header
          namespace: traefik
      priority: 11
      services:
        - name: argocd-server
          port: 443
          scheme: h2c
  #tls:
  #  certResolver: cf-production
{{ end }}
