apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: argo-transport
  namespace: argo
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http-route-workflows-local
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`workflows.mars.stargate`)
      kind: Rule
      priority: 5
      services:
        - kind: Service
          name: argo-server
          port: web
      middlewares:
        - name: standard
          namespace: traefik
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http-route-workflows
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`workflows.interpolar.ch`)
      kind: Rule
      priority: 5
      services:
        - kind: Service
          name: argo-server
          port: web
      middlewares:
        - name: secure
          namespace: traefik