apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argocd
spec:
  encryptedData:
    client-id: AgB9mjOehqFd94tCGkr0W0GfGQbmpxm1qlJRiseMjkJMGxaI3eANsEaVJ2T8NBQ1P5YAH9UeZ13bzZ9ReA1v/ds+E1hUaBIxDvniKQCVThrgKgjyAVn+7bGLxpOmzGSTMSj9P37EO4K96NwQPe2vCbBumB1h172XWYeRtGuCp7cSpkZxAWM7FO6cdGbz113MdK/+YgHGsXKrWRQ6rZcuo8i5ILdGbY9he9e6nsKz6Xa72rVXiKaEkTJiF8LnvsNJW6uKDb4oHCvviiXnAzS+VbA9xqNvVgUFapiWdPzQJz5aC2iZ9m3MwOuZ6MKTgadwF8IXNursqAIgCrzOPyTeABX2zPRJoq7ziU1GGtd5TMqHvAMRRRFBS/nMQaIn8/QHKSGl1vnhVKEO7RKraPsAaFIhOV+xDMR+ey9Rp/xB4idcJPzjZ5xVasYJjM7fMQcwZlopMw7VEaOrWwcXvREVpdrDGPcHSPfEzfL324dh8nSYwqnTjgNoAQQqrqqwax6srblIuzteCsuV5zbW8L0N5gJpFUdp086wLVTeS9LKH28FJhYFrV4hhpeHpGaAerTTtcyTje7p17GbZFXIP7qbglqG8ymrYZae+nVHNrE5HTWM0LvMGKVbiA9Lb56liV1Cq4AzGKnwUNfwUExQI0RZvDTtpBirj979MfULapCwH67MLJa+0rW1WRskd22PeqU4PuszmrpPUYz4uclvQMw81lLwMfI=
    client-secret: AgDdn9NJtm5Jz7JXR1g64QAkE08XQSbMYNRNElnMH9HI8JBjjG/+51mMylq5PomQ7cDcbAcZZouJ/eesLptMhmm50zP/ziByt2iGQNouQbeM0vJCge1uK0OSLzdGAuTXMv98E+MBCpexDpNPCzQZWshtzrjeStNcl+LatCAXUr6s/A5hN7646nGoGfTtTXBWhoM0N+7XHpeT6yLxAVE7yvG/kB6SZsF+LcCIwFpBUuMW6908Zhjqn6WAeVo3phwDXPN6ksYuZmYJ92FOB3rA7x946Br4mlomRlAE1CPwcqmr0PqsKdW/bVPy23ziJ3ujSIvg+U0/MIW46abSRcd//RGPq12MoabAmb2ke95j5Z6/4xrydBDR7gYmB+GsNtEkcfXfNs0k0KP0PAPf+FnX5ENv3BOBWXOXR8rny6/v2rQEbitls/5i46Cgiy8Sue4+RubJEbpe+iQYxtWcy9d9aBt1CJnJpJvP/i3PAOjEWiuF6yfvsiK+VP1L1dHMv68TUWdWpissKKMZnfCjcQtVq8zN4vfcMDyaWWYi0AILfBIv6pL7F5R8g0TqwtJmJLl2vbu6sliFTHhz1tmWL47Cn2kOrgDbTN4khF2fozchF2lGyBp6nzEvx39yPPit9onsnMGMTzuJgqos/BlLqO3FU6PVIUCPLej6y1wwXRmzgTWY8eg6HIGOriTp3waLF/x4SqIMLWgdZ+YAxP0VRVLtdKHKEP2Jt8MXF/IgCeBT
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argocd
    type: Opaque

