apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-gatewayaccess-secrets
  namespace: s3-gateway
spec:
  encryptedData:
    access-key: AgBz27cEjG2hqaObaIfYwuB9CyjA9Ppz1CZrKeIa5fh+h0Divc2CvXIwEQqWEAUVG9ymPS/4rRWcF6V/sfT/jJ0EQbGFO1m74xmE1fRjbs7FBAZR6jrc6WeEEaKPtsfH1xcnpT64AojGs5sI/FlbXWhyxonHEiaoDZdZGLVxPuAgVtGbxxCCV6IZWlS+5NFbUCV6UzeYj22Xpuw3sKHfEH2+euAyMairSKSo6zfCXQ8gQGseX6d7G0mzVgMLZ7gwUZYe6pU3aCNjObMjRUifOWDezT7fqNkiCiWJEGyul5RnHNUsXbyCewlXotDiXqRO2PSmZY1nx/iLB/9h4wPjr4WRuSDuiNEpCs+JoNuKbkAKp5YmyUUjhvCLYggOw1dQf2PeG9b2ngJc3Ch2qRNqF5zKNdf7F2mHTteHsnYRs6IB1D9rVxHjDdSANgP3D+9OUuXEzTGm5ZacUSbn29acPjU62DVNRUHmjhj4YY9dJ9XjphDFIqYG2wExqCJJ33ozKVTzZvcaBhfk5QogVb3xDlZKn8fr9ocYPKvgds2zV8XruBlU51AXDfCUmSZxVl2cVOCM7aFP1ipn6PELIWCB+2xrVGlisBYbNfeauoq1lqMDni3jdKtuuBEvptOwMIo2w5qoU+upWuSH5Qmt+1HLDoJ0d69gQ5k5S9iKqxryR0CRIZZTXumHERbdVrb5UjV42W68FBpOYakdtQ6Lkr5fZS/9H+AMCWric9xFdm5msTk=
    secret-key: AgAcLXwcZQ0PcEHID5p1+rVjbfKVGV/0E218cMmQ8om76elEBWFJpm6IlNSHqzj+yqmhPxWNGF/l6GXtmgTfF4k9BhZeIU4ZcfUORlOVZh9ghM53UM5TdhYlZtfCzA1sGZS0ovQUymQb+RQPIowxGP/2Uo5NZZBhVjpnv+qiR6CrnoRlgdZCL029LP5O3blOtAGTDBfunW5I7w/Hn25ws/PR+BQbx/sbyT6BAcO82T+gprAPLhTbh9DNIKFwykELBDkRYzKhXYBq/3qr2f+xKWYCDcMN8xkH1kbl3Mx5NY+GB8OQRhsezATYlZ+R8gXgyV7KC+gzwAAAOoYKw1Az0qrAGP3HeWbfSQIiEpuiFGB8OlAf/nDFzVSAuh5cw8pnJqCJxem53axakFI/+3T1bLfdnynnCfxpqZwqHB6/hB+u/Pmbwv+Nyyy/9dKmHL4Uy7YllNzceo8CuQ/zcuRISH7fncj25x8Uy7rA4Q0UFJmxKrHX9GfAOHccsj6JiIsGV+jyEXw/mQNcVjWx753F2KFJqWo8tQC7kpokLo6FkMv4Dn6MBgcg9BkAE3gM8bPi79l+E6iy5fDsQXj/iQdLyIGTKjvmZvlYT+YMdU62svr6wqk9PeZ/xDSqpQ7lvqrfW/mU6eii5ChD9GT9aBISghyY2HbQjSnDfNt/LduDOHcjo87lB19XlEaj3oZCX/dE7M4DNyO/jel85wSSSWCe33tqHkKZd0AQT7DNAZHPzNZXU0THg//k41ct
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: s3-gatewayaccess-secrets
      namespace: s3-gateway
    type: Opaque

