apiVersion: v1
kind: Service
metadata:
  labels:
    app: adventscalendar
    component: postgres
  name: postgres
  namespace: adventscalendar
spec:
  type: NodePort
  ports:
  - name: "postgres"
    port: 5432
    targetPort: 5432
  selector:
    app: adventscalendar
    component: postgres
