routes:
  - name: kutuapp
    domain: kutuapp.sharevic.net
    port: 5757
    portSecure: 5757
  - name: kutuapp-waf
    domain: kutuapp.interpolar.ch
    port: 5858
    portSecure: 5858

kutuapp-waf:
  replicaCount: 3
  image:
    repository: luechtdiode/nginx-naxsi
    tag: v1.0.1
  defaultAffinityRules:
    enabled: false
  network:
    http:
      containerPort: 80
      servicePort: 5858
  service:
    type: NodePort
  resources:
    requests:
      cpu: 0.2
      memory: 32Mi
    limits:
      cpu: 3.00
      memory: 128Mi
  volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-cm

kutuapp:
  replicaCount: 1
  image:
    repository: luechtdiode/kutuapp
    tag: v2r3b16
  network:
    metrics:
      servicePort: 3000
      targetPort: http
    http:
      servicePort: 5757
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 0.50
      memory: 1.5Gi
    limits:
      #cpu: 15.00
      memory: 4.0Gi
  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 10
    httpGet:
      path: /metrics
      port: 5757
  readynessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 10
    httpGet:
      path: /
      port: 5757
  envFrom:
    - secretRef:
        name: smtp-secret
  env:
    - name: X_KUTU_SECRET
      valueFrom:
        secretKeyRef:
          name: kutu-postgres-secret
          key: kutusecret
    - name: X_DB_CONFIG_NAME
      value: kutudb_pg
    - name: X_POSTGRES_HOST
      value: postgres
    - name: X_POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: kutu-postgres-secret
          key: user      
    - name: X_POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kutu-postgres-secret
          key: password
    - name: X_DONATION_LINK
      value: "https://kutuapp.zahls.ch/de/pay?cid=2eaa5545&donation[preselect_amount]=:betrag"
    - name: X_DONATION_PRICE
      value: "0.50"
    - name: X_DONATION_BEGIN
      value: "2024-04-04"
  defaultAffinityRules:
    enabled: false
  persistence:
    enabled: true
    name: kutuapp-data
    accessModes: ReadWriteOnce
    size: 10Gi
    annotations:
      pv.kubernetes.io/bound-by-controller: 'yes'
  volumeMounts:
  - mountPath: /home/kutuapp
    subPath: data
    name: kutuapp-data
