apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: acme-provider-api-token-secret
  namespace: traefik
spec:
  encryptedData:
    dns_cloudflare_api_token: AgB9JycAkrwVrhvXpIQcQJlSoqmjgqD5wofCodlRitj8MjqAkN81Q+aOxDnvtaLyluueh9ckuX2uECEos1QdEDSuE4UzRbwgs1lJro99VLOqQroR1g2To7t0oZ4ozAPqprvCRH7WGVEii+GrJjXUFTKDUrBPbxtvVCGooUDhTdXYEhE//fqLEkJm3A1CFHbQFL31J17P/4snWuYJlz38mf7++f3mdtaQ1GdlskYDCLULjgRMfnMcKBsA1piAkapGvgy68ENwxjN9WDwABE19iNK3pvaAd5I/xJSKhWYerRAS+p8NGi//Dz+yR8/o0YeO+as9qyCkROwZCj2FEU1zfjZfLj2KI918Gu4Flds/F6i4luoNzg/QYMbj2WPpNXCTQebX1+fBtBkPLkiFTtkhkNIiuc04CR/Y5eyTGRhvAo+5LwGr1I5WPPnIMn5T2oS2PTO+w8fZ6NDA5q2twkbhkNHzaibE4DV1gBrqS0shjlDFTgDRJqbZuUSqGRJWsvmUQpJwTVAveoQG/Wy82Qo/yRMESTJ5iOhi50DWM11XF4IxHSWMLXCYG+YIKVCXcrr9ljSzY7OBSOsfb/ScsM5JlSDkqB3Xi2b5whuiEeW8TOMU7sYkWWDBrwpElAkDLAmotOgSsTbAVCmuoGIQmoqE8D4biZe+gAiRpVAuWiYR/+9UZkATYXP7DCf3aGsUc709tT4uzkZlhyIeE1qEpsA+6+vuSJ4Bxhh03GDIt/wlfs8AOmBdPIrF+jYNjA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: acme-provider-api-token-secret
      namespace: traefik
    type: Opaque

