apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: acme-provider-api-token-secret
  namespace: traefik
spec:
  encryptedData:
    dns_cloudflare_api_token: AgCEq8BrMaHzoDP6iTRPAq8RTi8FYFMtkiBOFC0NDPaa1aQog0R45wnsK9LAGiNf5m2/hSi5UaetH+VWol+5jF2oByEO7RYqK+AuAg7Eg4HVLbapaDpClaW5lfbgTW1M2uEQCg240QlXQnbCTFKPIeiBM5pxp39mAb7Q3DMeY5ZQPAEAfE4ePOcvzH9zGgQq1/ZhNJiyTkWIjZjS5L7M/fl0zBx47J/SHkn4vB3Mh2ExRXp15qZyqJpqeMiJzcaENPuJOmXB+VoY8V63Agu2d77Eb/OEw/m59i1+frfwPAOeo8SMPScUR5fa3sJiiR3DWYNEH0SbaPSo9Q4G5nsokGRPmpmrYSejwR98sod/VVibgE6UIKmWb6k/4u/PfIxoicoN4K9od3VcULv3fWtLaTt2LnbvLBHX4jYNtqoqyG1/yGWW+RgrFgdEOy/krikkVNvl4PyJwOSoh7yQ8bVK14RLTq6Nt7IZjmlvUsdfngGFDFid623cMy1sWTX4XJhDZuelTD0JsCFsBZNkeKpC3jyiwXC+ybsH2oXsxLdr8KtG1owzznS15xqiPMMG9DuaAOgHTPgKm0dk31Zf2Sh3mxWlVWaBtz1lRusEuLVZPat3HVolcUg5MBSJ8/PI7FserCu+V1TPT+zhRiaMa5cAEqXdqVhjbCbYbrpiIAb4hQJodujrcewX9SYFqIeIpdhXcABOjLTXlZkR90u7tSsdSXGPDVrvectUKU+aEBNIJwxEbQneQOY98MaanQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: acme-provider-api-token-secret
      namespace: traefik
    type: Opaque

