---
{{- if .Values.templates.authsecretname }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth
spec:
  basicAuth:
    secret: {{ .Values.templates.authsecretname }}
{{- end }}
