{{- if not .Values.templates.skippodmonitor }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: podmonitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  namespaceSelector:
    matchNames:
      - traefik
  podMetricsEndpoints:
    - port: metrics
{{ if .Values.templates.dashboard_hostname }}
---
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: https-probes
spec:
  jobName: http-get
  interval: 60s
  module: http_4xx
  prober:
    url: prometheus-blackbox-exporter.prometheus:9115
  targets:
    staticConfig:
      static:
        - "https://{{ trimPrefix "https://" .Values.templates.dashboard_hostname }}"
{{ end }}
{{- end }}
