apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: standard
spec:
  chain:
    middlewares:
    - name: compress
    - name: limited-body
    #- name: max-connections
    #- name: ratelimit
    #- name: circuitbreaker    
    - name: security-response-header
---  
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: secure
spec:
  chain:
    middlewares:
    #- name: http-redirect 
    - name: standard
    - name: more-security-response-header
    - name: x-fwd-proto-https
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: http-redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true
---    
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: x-fwd-proto-https
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"    
---
# Enable gzip compression
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: compress
spec:
  compress: {}
---  
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: limited-body
spec:
  buffering:
    maxRequestBodyBytes: 2000000
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: max-connections
spec:
  inFlightReq:
    amount: 5000
---
# Here, an average of 400 requests per second is allowed.
# In addition, a burst of 800 requests is allowed.
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ratelimit
spec:
  rateLimit:
    average: 400
    burst: 800
---
# Latency Check
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: circuitbreaker
spec:
  circuitBreaker:
    # expression: LatencyAtQuantileMS(50.0) > 4000 || ResponseCodeRatio(500, 600, 0, 600) > 0.50 || NetworkErrorRatio() > 0.30
    # expression: LatencyAtQuantileMS(50.0) > 4000 || ResponseCodeRatio(500, 600, 0, 600) > 0.50
    expression: LatencyAtQuantileMS(50.0) > 4000 || ResponseCodeRatio(500, 600, 0, 600) > 0.80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cache-header
spec:
  headers:
    customResponseHeaders:
      cache-control: "private, max-age=0, no-cache, no-store, must-revalidate"
      pragma: "no-cache"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security-response-header
spec:
  headers:
    frameDeny: true
    browserXssFilter: true
    contentTypeNosniff: true
    accessControlAllowCredentials: false
    accessControlAllowHeaders:
    - "x-access-token"
    - "Authorization"
    - "DNT"
    - "User-Agent"
    - "X-Requested-With"
    - "If-Modified-Since"
    - "Cache-Control"
    - "Content-Type"
    - "Range"
    accessControlExposeHeaders:
    - "Content-Length"
    - "Content-Range"
    accessControlAllowOriginList: [ "*" ]
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: more-security-response-header
spec:
  headers:
    sslRedirect: true  
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    contentSecurityPolicy: "default-src 'self' *.interpolar.ch *.sharevic.net *.advents-calendar.org data: gap: ws: wss:; style-src 'self' 'unsafe-inline'; object-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.interpolar.ch *.sharevic.net *.advents-calendar.org www.google-analytics.com; img-src 'self' www.google-analytics.com *.openstreetmap.org data: *.openstreetmap.org *.fbcdn.net pbs.twimg.com media.licdn.com *.cdninstagram.com *.googleusercontent.com *.akamaihd.net www.google-analytics.com;"
