{{ range .Values.routes }}
    {{- $servicename := .name -}}
    {{- $servicport := .port -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: https-route-{{ .name }}
spec:
  entryPoints:
    - websecure
  routes:
    {{ range .domains }}
    - match: Host(`{{ trimPrefix "https://" .domain }}`)
      kind: Rule
      priority: 5 
      services:
        - kind: Service
          name: {{ $servicename }}
          port: {{ $servicport }}

      middlewares:
      - name: secure
        namespace: traefik
    {{ end }}
{{ end }}

