routes:
  - name: adventscalenda-frontend
    domain: test.adventscalendar.org
    localdomain: test-adventscalendar.mars.stargate
    port: 3000
    portSecure: 3000
  - name: adventscalendar-backend
    domain: testbackend.adventscalendar.org
    localdomain: testbackend-adventscalendar.mars.stargate
    port: 7007
    portSecure: 7007

adventscalendar-frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/mrcode97/windoworganizer-frontend
    tag: sha256-0639e0a1557597697a72e58970959aa4c3bc5b885aa00554c9cec9e31d43e5fc
  network:
    http:
      servicePort: 3000
      # ingress:
      #  host: test.adventscalendar.org
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 0.125
      memory: 128Mi
    limits:
      #cpu: 3.0
      memory: 512Mi
  livenessProbe:
    initialDelaySeconds: 5
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 4
    httpGet:
      path: /
      port: 3000
  readynessProbe:
    initialDelaySeconds: 5
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 4
    httpGet:
      path: /
      port: 3000
  #envFrom:
  #  - secretRef:
  #      name: smtp-secret
  env:
    - name: _NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: REACT_APP_BACKEND_URL
      value: https://testbackend.adventscalendar.org
  defaultAffinityRules:
    enabled: false
  volumeMounts:
  - mountPath: /adventscalendar/lang
    name: lang-cm
  volumes:
    - name: lang-cm
      configMap:
        name: lang-cm

adventscalendar-backend:
  replicaCount: 1
  image:
    repository: ghcr.io/mrcode97/windoworganizer-backend
    tag: sha256-75bd8a24409959ae8ba58ff02aa831149d0cc0b24473856914ea385c742ce17c
  network:
    http:
      servicePort: 7007
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 0.125
      memory: 128Mi
    limits:
      #cpu: 3.0
      memory: 512Mi
  livenessProbe:
    initialDelaySeconds: 5
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 4
    httpGet:
      path: /
      port: 7007
  readynessProbe:
    initialDelaySeconds: 5
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 4
    httpGet:
      path: /
      port: 7007
  env:
    - name: _NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: dbsecret
          key: jwtsecret
    - name: DB
      value: adventscalendar
    - name: DB_HOST
      value: postgres
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: dbsecret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dbsecret
          key: password
  defaultAffinityRules:
    enabled: false
