apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-workflows
resources:
- base/install.yaml
- base/argo-default-crb.yaml
- base/argo-route-service.yaml
patches:
- path: overlays/argo-server-deploy.yaml
- path: overlays/argo-binding-crb.yaml
- path: overlays/argo-server-binding-crb.yaml
- path: overlays/argo-sso.yaml
