---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-config
  namespace: rclone
spec:
  encryptedData:
    rclone.conf: AgB6fQwV2KOvYv26hDp3nldP8wQTGYh5PJC6vtGkyMAI9zcHq/Bkm39qeYSewVPprVsnnYsYtmvnJig8RReJXJduXnnvh+OqJOxsEHtkoNHjDlD46ku/L9NMJQbwr+gtfCngJ+p2I5/La27YKxvX5xbVPv1DYgzuXpZlEW/uyfk3B+Hw+5jK+oKhaV+KHpH2Gj8Z1y+FYdghudMom+SGgdL/GBa1x7LZ+6Sk3EF9pjthMZM9dM311ImcLd+6t67w4ZytSry2atZsM1cwZWG2vHYVdWUoj4ijvbIgPC76HMDO1u/Ew/N/m0xnqlF4lHHFCJN4WxE0yFVG3E+hYdfgm9/f/wQ1/ej6Sdyi2HX5BcVvXEF8JtAxi2KZz66DXQ1Er0BrImwO8k3buJ9AQaQP55zriyEMJd2shXiqnqz5AlhGJJ9tE6phiTac8xirKihBMpypLwaotugv8Ul2LR/jH39ACGhGKxCpUCPyDWJ0gJFqAXcLrP2Cj4OJiAobObZ/v44vAKEGtapWLBuNKBeWRtpuZezbEcBcPP8RHxPUxm5Hlo7q8cspx37Gy37BsIcoD4WINCa9nIEpTQ5AleHLSumAwFC/xC7QytujFa/sNHL3cAgrI3+wmojmuNAo8S8ysxkfnv/TEkz/QDuUlfooOXRE9bhYwUx29campKtiN4LvEmZcl8LLZbfri/9bJ0Ymkso26hY0YioU6/9OTZ0O08AmEiZyw6QlR9jlfevn5gxWoFuPrLppyhCpxZGlBTQd6YdPvk/wJQ3buz4qa26gvZmP5LEAbV+m7RS1Pz7Bz7ByJHbi0RE4GiCDnAkVttxMwHGxEkTG+Bmv5Ch17d602/xv1elifOl9hQI7llw6L4FY2u3ihGdTZivDq5YN72Auby1kefvEw7KQakGsX2Msoj4ksIpPOjnFjobY1powmnHH4lMvvM/pFKXIm0xGp3at6WYDTXIWSvWyWTtiLm0tozxPSUNwtRqift2AC445UGBx+NZsCCg1gQtfjNvyixUBOdWdigwkxMlrT4ur1ZGqKyPUAfLh1rqoJil5ACdn9AZo+pjAh1f6g413sVIdU2y0V4wXLFIweI64WE83iot74LTOqV2HhdPqILUFdGhuohJViD6jqY3YMhrEy87BXNJxlvwwrzFS7MwEOX5hSxHJn7Evy0bT5bfiM3qFUcwtxlDR5++ytNbnO4xuVbRQlDH3/Zl8BRTikUrPB2nfAZEZ/MJ+6Fk1PZMqkziqnmciN3dWfilrBVx74W9KjminhS0lumXvNfD9ZvSj+udT7x0=
  template:
    metadata:
      name: rclone-config
      namespace: rclone
    type: Opaque
