---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-config
  namespace: rclone
spec:
  encryptedData:
    rclone.conf: AgCbFvspy0lq656Ri8pLuv2BREUyuD5w/vHBECDg3OrAbfElo5cct1WklKYsIPhAa9K4PE2aqCl3y84LZKcJEdtIeRbRYjFeJMOANj/exquAVBh2GDkEihBiUzMwyNkNL24UyTc5db83UGZnIXiSW9VcxkeblvOMuD/Z1iQylRORIK2SrgcpviYrp8joXlSuikIWnwPwbSqd8Q3lnjcwTRXrgQFBo3rl54qfd98+tJOegJPeuh4q6B1px3cF6U27Nw/of1/DaskXEY5jVLC2GK3HJvmVdzHTxTe94+PISc2ZWdW1EJ1898PsAGZ27U9zM1XExBqjUNvuXUHTr+rDNOHqM+eBFxCHU0/+F3lpO2XjvtqoboY53/ut5i9Qsk5jtbJGxWpRGDMnRLYgAk691LCm5UOrEhE+Kl8Bo6lH3r53ULXb6bzs522072pI5rfeqHJ9WLuB8s82VTYV6mk/RlL9v2MpytX2BZdEQJoUsG/jp4ASw5QdfGGSO98Jn39iIWikLGEzPYhEeErXlMhU1sjiKbU/tSZEG91/nkxyKrY2iMhPAQa5YcTCv+n0ssssRDrZM+xIaqPuQJ/WCZfZaqERV+pTxClN/3WdkdpFOyKhTUxOBpKKSEQPNOHY8u5ER4csyuXSzMGjVCUoMlJg5up5AIst5Br5DStbEXxlSCx8Dgw6dT4qhVgVl6MginAevXJLK8VGX86HjzKCZ2giHufg5w3wQ60Q2SlCteeArP+yNAxdAeuhN9j5J1Z3m3Osg2FOUcb0n6ul/0Zucz8vKkLVou5IqKs7FiP7p+D2INKmYtwYQ3rd9ghv8fMMa96RbeRGTLQHr6sNkVj5COimIv69qSCHV9KXAVHkr43WaNrID9+bNssSRpw+6o8r4NcT6J7XQpE8nFUx00Ft+/QklQCceDodRlFLT9WUTjKTXg9ZSU9Jq09jfwdi/TlzHQuG0jzPKD29q2W8OUcabpp4ZmnhDRdUPGF+XlzxADmASjnyFFPKbmQ2lCeHGmBYIxESqQAWgzG8qoEEtftURMQh7XXPA96LBb6FtlKEdcgjAUorZlojgtCz/6spmepfEpXbgVxnsomlqTQVkFZGEH85m80SwzRwpLi6jH4m0wZ25LD6xzq12cWmOV24Hw/r83rXnjnP/13Y3VrBnwViuDMr385Oj4GCBh6XROMxq+YXllFVT1sAhqWb3CPIkfr+OdlTUgd6oyF/7kWAR2geTE8l10XEm4XDXvOQXjQaG9kkyshT5VZPfvnvzhK3pLGX1K4vNDqCvncjZZ5bAc+/Q1tS0oiW1tWSR4JqWYAaFBUzkIiVkBr6CFU8n/sc8/ZtMrHysM4LniY2c62E7UaUNyqjQQ==
  template:
    metadata:
      name: rclone-config
      namespace: rclone
    type: Opaque
