---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-config
  namespace: rclone
spec:
  encryptedData:
    rclone.conf: AgCsreTQiZ8PFAab4b23AOoStVy0mW51Uv/wPqW6Oa0g6/ERNQfm8/a9uvzHrEB/XRF7y2CDxkvsJIRoYm6DPTSMeNgtsbykU315yaUVu6OAitQr0QrQRi5uoiZcJhQUfUTfVIFyfrkzsQ7v23HgRRnFpgQD/KRldSv+QX68e0a6iwM/YqBfSpTG1bhgpIgP/RisO0isRGoNlgC5qCAm7JqA8UAvIGuGH69i90qMQ53+C2y0iXJeXKnxNO7v7LPR06zMPuJSit8kvULFPNmcD1aU4FAyXo0qDvEDwp54+IOXbUZgmGiXl5U7k72Sry0rvUU4djMNa233VIA9ggVofKKdDYrHo9X/ZmjWSlfc2bNSRfyy4PNHuVwCigUm6pVaXSF3QUtGZOC8/HW/HGmOs1VMkFQ0JO/P3EMBIDV4fD67yeK3r98e/vACv6sKyIj1M2Tb2HOf/HnM1tXxED20dehJxHd6JVJwFTQz13iG7FFlWpteibXIrh9hewMYFe3bCFiTP6Va8DxFn2edllo52sm1yHGn/qAaSJbyI7ze3RB5e3dn8lt982+pUpGaPHXhdGWxGVUDZqRKOLu7zetG+SLWWPmLAW9K8dNHp1k4lwu9nK7K19/9dpWwaMTF/KeQVcaWe3NGvTCYAsiY64OoQsfM/GM0TDGXpKLpj7qJSIZw3IiOlMR/U1ogOBwA4dEulUCfDmU5XnB2PjQ/TWMLVZB8/rMa+Ran0xG8afV7tbMMcpuEtLILlCorVswdHEZK43xO86ULUqO4Jx6+50O7c7pcKxLkEYueI2KVLRZ3wF4sfsTEv+HElvmk4rCfDpFnbwwVtrH+1zNGtXfSBTvoGIeLzA1xqo7qEFO226xy3H0n2I+VprXgk7VZs/7L04f+FVRAa+nfSdew2kbQH2Iz4MxV4OYxhiasT+X0cQILstdpU1Or/ER0RjC6CTRQAND6yEAn+dGJ2G9dz68X9eISRHyJ5pr6iq0+0/rWXcnKIKUHTBXWzsrynNxaRwcii6YThDVqOVSekHEhHsDfVzLvi5kZRVg9t3kTD+dAzOJfHp1ZmIE1eazsMOAZf10/753SEgSuCeU6xD5yWR9Kit9h2EstcMDolacr/z4RtnpdqXJJkBHPJ9YJbTKM1GoChQ1O4TCdjhsyiHyV2nTj2MxNzjCxeCXksPJ4JVKMqyQAMCZZzN4lOPtVaVCtMC7hiiHeWAzdseQKtCX2sAsG0cifFcmIlW1dd/T0+pPyjll1NZWblWf1Tx1ahWRr/klJrqYN/PSTOCV1N9zxiI0zW65nW97/S9SJtHhVHSLiqY2g0LHYPxWMlq6PgUomuaQZqSCAEemtRKwImTu9l3hde/8q62k=
  template:
    metadata:
      name: rclone-config
      namespace: rclone
    type: Opaque
