---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-gateway-auth-secret
  namespace: rclone
spec:
  encryptedData:
    RCLONE_AUTH_KEY: AgA7yNJtfGB9QMcZUPStjHGDGRoWDQxgkBGSZX9HEjvg7KLEdJjQA7WWNLW8eR9W8O/GYwRhWlA69so66datv/+8A9oGlcgZbed66s4ndUncVjEoPq+AooJLUkZNEvW/chdSQS2grWAbBoRwouCdA8FjrIMb9TcK7H3jzp3rOvsECu8UC0PTj+rV63TIai/5FbZ4YxBonDNV4+IDCzYaSYryRkYScTURTgccdRhS7/8XiCWuL4qb2oXmfSoEhQLMPhCCOzBtYv3E/QVlUACLgx6BZsJvbq6MzWpxEjtRhvVQXHRk1zjoIcergJONaCKGD6A9Mk0CHPEgyG4PHKj+BF3wIxXQQUR6HZphBOtct46cSqKXt4BkhVElsEDhkSrc4hVgRFEXwWb+ckq8Erf52w0OPzJEPz6sOpuavjeyCXRoyasFdvC6PmFG3Nq6VSyxJ9hvW5XbFN5xdFqC6GX2FtsdZlepzKUY5iCsRR5V00x9zlYI1/7LDyo7sHBSbzkWgLhu8Y2vpH2tasl5cjYY274aadaXX86fxoqw1UNH9FdF5ALgfFP3PPHV3y9amWgQECtHU9pYNwmwMZULNn62VTu/Ucq4jsIX38k9yIRwEj6ycx1YuLFFnHNc56Dpevlindy56euIIFBL+gMeedj+xn5tqf95rrj+JW2fvj357dsgBHpbZhOIM+M1I7GqNvQdDzoGWkm6HspQ/hR65SceJt43i7eNmsNuhSdEroNPjIUsPAAkyIz3vUFfXvRRSWr+2i4b+EzjKfZavoqn3UdCiA7CPjhQq9tdmQ==
  template:
    metadata:
      name: rclone-gateway-auth-secret
      namespace: rclone
    type: Opaque
