---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-gateway-auth-secret
  namespace: rclone
spec:
  encryptedData:
    RCLONE_AUTH_KEY: AgCox2DD6rouXVzsco0kuisyKCJJDH4SQEBLq3c6/yc4it48VnCgh6Nj8cfC/2S8tlpkyRXfVSaAb+06rdtPutvF03LzOKawDL9FBsjHeLEUhL2MIr8HxQgz3s73McJEXNDFNTeNcqVrWAvTmRoiIC3pDtWNDmv+CkJScWfnTXTakN4roFs5ELxEkGbGtNzP/P0X4q6hrbcVxZieiGfU2Y1VRipQyrpSWwNnhWy6gNlRLSG5/13FVpz4iSgzBsptbj3iFscRYHt9ShyRPGCnF5fkXQkds7wLnjuAcjLSQUhuAKOUykAqTymbATtg4noudj39rAtc9CL8PgAc6PFazbkXBsQwvM3kYoyi1RiWXE5Zf6dqrKsJH052ZzYiPmM8KqW1Wjjd+qq00lKf3C2Ni0pEt6lGd69lt+xzsMgDPqHEBeZsCqe/8xjaxEhrcOKs/lZNWFIePqgV7SoWvL38kdjn8luRJ4HrutUXUtJ2+CFAVcO29Dj8uiltrDP3dQPpr5PQB10POCu+XPaMbdeuQ/WGbEuT8IUFxZMp83Pes5WQX29kC5uORe5gya8/kxRrNnX7V2Ul0R7bwwo8C+552tAoKeNWNHS5krXSHylTbalnBNM6i/jw+Gy7+lZ08cqMLmnNfbCOK94NtOeAQnZDzlIl9Mf+tRWVEZ72b2cJPdu8I1CRSyztd4e712eOzRD8ABHNmMKnopPLWMqdKQ784HyKuWzDI1dYD2GNK/vmM6nW5n+bA35oQeFoT8u00efjnYR6dmB9L9E88/5Ifww=
  template:
    metadata:
      name: rclone-gateway-auth-secret
      namespace: rclone
    type: Opaque
