---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-gateway-auth-secret
  namespace: rclone
spec:
  encryptedData:
    RCLONE_AUTH_KEY: AgCOBmU7Xl8t+XtTmTnQ9UPO2j7eCnvegphEwkEFi+vjvCmEuvXnO6GjrC9cvdfYCCB8U3GCMq91GL5MqYlyXfZ4TDxarmHFuSmC/Cicq9nIcCTBc3WMvLHauRc7Iss++qTdM5debgWKsSi+4GmWSfAclm+x5+nXWA5e1JXDsZObmrjAKtDiovB442qlndfxYRN1o/bCuKGUs9EaVT9TrMjrnobGChPtOTBKlPtj3t8m2zw5uy4JBYcqBsqHCwP1vngF01ETfwbFRDVQ1Hu1UGfczUgxm56gWRdZOLWhZpxdydpcfPaDvFs+HDWT8IV1WOWSp+rWqFrdrX6D8b4entRN93rYpOjoj24FL0FvuaxThrXO6DaIzxazZ1LKYZt9rpxf8iac9uBaahZ5hY3GcIeUKEAs3+FTWdj228tU55o/8FMQCPeq/IDcPM0iBWo/mASIiqwcKtInw6nPQ8h4kZ7lIZselbuL+YgU9d186tQVejPqdigMZJzssmN2WUvTs/wvYKRsToEta7KOGF5fhCxlaeyNMely2TG7xH2bIKwJxVXShzgdKVaMyN4DJOq+k5PnRHQX6fmhv/L+H5XGtnVE4xfbM/Dlvsvd6cPgre5cpobwuvGBjTns16H61E/0nucjKl01ChEUT1Iq/bkioJBDG6qa7TVC0aHsx0iE38fNs9tta+O3eiaDRG8wUdTgjGaVlf0gAzAYA3xteH/t1JK8W9o1e9J462AWGu16wf5decMF1TQz+dDBJNE2cA9RRsbmRqGfA6iU/Y+zGmUP4X3h7brVHPNIKdgUhpk=
  template:
    metadata:
      name: rclone-gateway-auth-secret
      namespace: rclone
    type: Opaque
