apiVersion: v1
kind: Service
metadata:
  labels:
    app: kutuapp
    component: postgres
  name: postgres
  namespace: kutuapp
spec:
  type: NodePort
  ports:
  - name: "postgres"
    port: 5432
    targetPort: 5432
  selector:
    app: kutuapp
    component: postgres
