{{ range .Values.routes }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-ingress-route-{{ .name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ trimPrefix "https://" .domain }}`)
      kind: Rule
      priority: 5 
      services:
      - kind: Service
        name: {{ .name }}
        port: {{ .port }}
      middlewares: []
        #- name: secure
        #  namespace: traefik
      tls:
        certResolver: {{ .dns_resolver }}
{{ end }}

